<Project>
  <PropertyGroup>
    <Version>1.0.7</Version>
    <AssemblyVersion>1.0.7.0</AssemblyVersion>
    <FileVersion>1.0.7.0</FileVersion>
    <InformationalVersion>1.0.7</InformationalVersion>
    <Company>Remote Desktop LAN</Company>
    <Product>Remote Desktop LAN</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>
</Project>
